### PR TITLE
Fix for when landing page id is not set.

### LINKED ISSUE #116: PHP Notice Undefined offset
The `WP_Convertkit::page_takeover()` method is throwing this PHP Notice:

Undefined offset: 0 in .../convertkit/convertkit/includes/class-convertkit.php on line 260

It needs to be updated to handle Landing Page set to "None" which is index 0.

### LINKED ISSUE #120: Undefined notice
"PHP Notice:  Undefined index:  in /app/public/wp-content/plugins/convertkit/includes/class-convertkit.php on line 265"

This happens because $landing_page_id is empty.

**Update**

This is still happening in v 1.6.2

update when fixed:
https://secure.helpscout.net/conversation/695907738/289964?folderId=956509

### PR DESCRIPTION
**Pull request by growdev**
Closes #116 
Closes #120 

## Summary

This PR handles the scenario where the WordPress meta `landing_page` is not set on a post. This would happen if a page was created in an old version of the plugin and has not been saved since.

When the page is loaded a "PHP Notice:  Undefined index" is added to the debug.log if WP_Debug is turned on.

## Pull request checklist

* [ ] Is the added/modified code sufficiently tested? Do all tests pass?
* [ ] Is the code easy to understand? Does it follow [the rules](https://robots.thoughtbot.com/sandi-metz-rules-for-developers)?
* [ ] Are the return values of public methods documented?
* [ ] Are any complicated parts explained / documented?
* [ ] Does this PR positively affect the code climate GPA score?
* [ ] Do you want feedback on anything in particular?
* [ ] Does this require QA? What should be tested? 

## Ready for review?
- [x] Add "ready for review" label
- [x] Assign a reviewer (or two)
- [ ] post RFR in #wordpress

**Handy links**
- [PR Checklist](https://github.com/ConvertKit/convertkit/wiki/Pull-Request-Checklist)
- [Code design](https://github.com/ConvertKit/convertkit/blob/master/README-coding-style.md)

### CODE REVIEW

File: includes/class-convertkit.php [hunk 1]
```diff
@@ -244,7 +244,7 @@ public static function page_takeover() {
 
 			$landing_page_id = self::_get_meta( $queried_object->ID, 'landing_page' );
 
-			if ( '0' === $landing_page_id ) {
+			if ( '0' === $landing_page_id || empty( $landing_page_id ) ) {
```
Comment (gammons) [inline includes/class-convertkit.php]: in what case would `$landing_page_id` be `"0"`?  Also, can we cover this change with a unit test?

**Comment by tnorthcutt** [comment]
@gammons since this is fixing a minor problem (stops a notice being thrown/logged), I'm going to hold off on including this in `1.6.3` until I can poke at it and get my head around what's going on.

File: includes/class-convertkit.php (hunk 1 above)
Comment (tnorthcutt) [reply includes/class-convertkit.php]: `$landing_page_id` is set to `'0'` when a WordPress post/page is saved _while the CK plugin is active_. If a post/page is saved while the plugin is not active, then when it is later activated, the `$landing_page_id` will be empty. @growdev's addition here checks for that so we don't show a PHP notice (which at least two customers have reported).
